### ISSUE TITLE
【倡议】添加条目尽可能简洁，减少解释性陈述。

### ISSUE THREAD

**Issue by ScriptBoy2077** [phodal/tangping#32]
### 个人倡议[1]：  
（1）、条目积极乐观[2]；  
（2）、条目归纳简洁；  
（3）、避免解释性陈述；  
（4）、若对某条目确有独到见解，需要长篇幅阐述时，建议新增`./content/*.md`并在主`README.md`中添加链接。  
  
> [1] 申明：本倡议仅代表个人观点，与项目作者和（或）任何组织均无直接利益关系。  
> [2] 我们选择躺平以寻找人生真谛，但我们并不消极面对生活。  
  
***  
  
**躺平** 只是一种 **生活态度** ，并无主观恶意。  
躺平不会对政权稳定、经济建设、人类文明进步产生任何实质危害。  
截止2021.06.08本项目star人数仅200人，在全国人口总数14.12亿（第七次人口普查）中占比几乎可以忽略不记。  
任何形式的指责、禁言、跨省追捕都将造成人力、物力的资源浪费，建议 **不赞成（或反对）** 躺平的各界人士将有限的精力放到无限的经济建设中去。  
祝 **祖国繁荣昌盛！！！**

**Comment by phodal** [comment]
直接来个 PR ？

**Comment by username2077** [comment]
> ## 欢迎各位**有志青年**加入神圣的**躺平**家族。
> ### 个人倡议[1]：
> （1）、条目积极乐观[2]；
> （2）、条目归纳简洁；
> （3）、避免解释性陈述；
> （4）、若对某条目确有独到见解，需要长篇幅阐述时，建议新增`./content/*.md`并在主`README.md`中添加链接。
> 
> > [1] 申明：本倡议仅代表个人观点，与项目作者和（或）任何组织均无直接利益关系。
> > [2] 我们选择躺平以寻找人生真谛，但我们并不消极面对生活。
> 
> **躺平** 只是一种 **生活态度** ，并无主观恶意。
> 躺平不会对政权稳定、经济建设、人类文明进步产生任何实质危害。
> 截止2021.06.08本项目star人数仅200人，在全国人口总数14.12亿（第七次人口普查）中占比几乎可以忽略不记。
> 任何形式的指责、禁言、跨省追捕都将造成人力、物力的资源浪费，建议 **不赞成（或反对）** 躺平的各界人士将有限的精力放到无限的经济建设中去。
> 祝 **祖国繁荣昌盛！！！**

建议可以直接新建 `CONTRIBUTING.md` 说明相关规则

**Comment by phodal** [comment]
嗯，嗯，来个示例？

**Comment by wuhaohao1234** [comment]
https://github.com/wuhaohao1234/learning-buddhism 欢迎fork，躺平的时候可以学佛
