### ISSUE TITLE
互联网没有记忆，希望增加原文？

### ISSUE THREAD

**Issue by warpmatrix** [phodal/tangping#39]
想稍微看下原文但找遍全网只有片段，不知道各位有没有存档？

**Comment by NoctuG** [comment]
> 想稍微看下原文但找遍全网只有片段，不知道各位有没有存档？

什么原文？？？？

**Comment by warpmatrix** [comment]
> > 想稍微看下原文但找遍全网只有片段，不知道各位有没有存档？
> 
> 什么原文？？？？

《躺平即是正义》，好心的旅行家的帖子

**Comment by phodal** [comment]
和本 repo 没关系
