### ISSUE TITLE
建议加入佛经和红楼梦

### ISSUE THREAD

**Issue by weaming** [phodal/tangping#46]
还有[犬儒主义 - 维基百科](https://zh.wikipedia.org/wiki/%E7%8A%AC%E5%84%92%E4%B8%BB%E7%BE%A9)

第欧根尼
![image](https://user-images.githubusercontent.com/10275711/136494786-044ecc41-c40e-4f4f-9801-672883e8394f.png)

**Comment by phodal** [comment]
红楼梦 有点奇怪 ？ 来个 PR？加一下犬儒主义之类的？

**Comment by phodal** [comment]
fixed #47
